### ISSUE TITLE
Frequent device crash based on connectivity

### ISSUE THREAD

**Issue by HexaCubist** [halogenOS/android_device_oneplus_oneplus2#20]
First of all, this is an issue I had on the stock rom as well, and has stuck with my phone for a while now. Normally I'd get a warranty, but the device was parallel imported and is no longer covered.

The crash appears to be based somehow on connectivity changes, as when I am at home on a stable wifi + cellular + bluetooth connection the phone doesn't crash and is stable. On my way to class, the phone will always either crash (phone screen black for 2-3 seconds then automatic vibrate + hard restart) when I leave the house or when I arrive at school (connecting to another wifi network). It sometimes also crashes on bluetooth connectivity change, and is particularly likely to do this when bluetooth is turned off or on. The same goes for WiFi - turning it on or off usually crashes the phone.

The phone will also get stuck in a boot loop sometimes - often when Wi-Fi/Bluetooth is turned on, or other times when it's sitting in my bag (meaning the phone is hot and out of battery when I need it!)

I know this isn't perhaps the place to report it, but I think the bug is a software one, so at the very least someone here might have some insight into what's happening, or ideas on how to fix it? I can provide any logs needed.

**Comment by xdevs23** [comment]
I would need you to root your device, and, after crashed and restarted, get me the files in /sys/fs/pstore/ so that I can analyze it and find out what's wrong. If you don't want to root you can try to immediately boot into recovery after the crash. Important is to do it after the reboot, without rebooting the device again.

But I'm pretty sure it's an issue on your side because  afaik nobody reported this issue yet. Can still look into it, maybe it can be fixed for you.
